name: Update README Tahun Ajaran

on:
  schedule:
    - cron: '0 0 1 7 *'      # ⏰ otomatis 1 Juli setiap tahun
  workflow_dispatch:         # ✅ juga bisa manual dari GitHub UI

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Git identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Hitung Tahun Ajaran
        run: |
          year=$(date +'%Y')
          next=$((year + 1))
          echo "TAHUN_AJARAN=${year}/${next}" >> $GITHUB_ENV

      - name: Update README.md
        run: |
          sed -i -E "s#[0-9]{4}/[0-9]{4}#${{ env.TAHUN_AJARAN }}#g" README.md

      - name: Commit and Push
        run: |
          git add README.md
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update README.md to Tahun Ajaran ${{ env.TAHUN_AJARAN }}"
            git push
          fi
